# Generated by Django 6.0.4 on 2026-04-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='identifier',
            new_name='uuid',
        ),
    ]
