# Generated by Django 6.0.4 on 2026-04-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_bot_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='platform',
            field=models.CharField(choices=[('API', 'API'), ('Discord', 'Discord'), ('Slack', 'Slack'), ('Telegram', 'Telegram')], default='api', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium')], default='Basic', max_length=100),
        ),
    ]
