# Generated by Django 6.0.4 on 2026-04-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_bot_group_identifier_bot_group_name_alter_bot_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
