"""create messages and classifications tables

Revision ID: 4e3709a50d33
Revises: 
Create Date: 2026-03-29 10:12:26.803543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3709a50d33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sender', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_is_flagged', 'messages', ['is_flagged'], unique=False)
    op.create_index('ix_messages_sender', 'messages', ['sender'], unique=False)
    op.create_index('ix_messages_source', 'messages', ['source'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('toxicity', sa.Float(), nullable=False),
    sa.Column('severe_toxicity', sa.Float(), nullable=False),
    sa.Column('obscene', sa.Float(), nullable=False),
    sa.Column('threat', sa.Float(), nullable=False),
    sa.Column('insult', sa.Float(), nullable=False),
    sa.Column('identity_attack', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classifications')
    op.drop_index('ix_messages_source', table_name='messages')
    op.drop_index('ix_messages_sender', table_name='messages')
    op.drop_index('ix_messages_is_flagged', table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
