# Generated by Django 6.0.4 on 2026-04-17 03:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('platform', models.CharField(choices=[('API', 'API'), ('Discord', 'Discord'), ('Slack', 'Slack'), ('Telegram', 'Telegram')], default='api', max_length=50)),
                ('group_identifier', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
