# Generated by Django 6.0.4 on 2026-04-18 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotHourlyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.bot')),
            ],
        ),
    ]
