# Generated by Django 6.0.4 on 2026-04-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bothourlystat',
            old_name='hour',
            new_name='timestamp',
        ),
    ]
