# Generated by Django 6.0.4 on 2026-04-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderate', '0002_rename_hour_bothourlystat_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchat',
            name='group_identifier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='textchat',
            name='group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='textchat',
            name='platform',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
