# Generated by Django 6.0.4 on 2026-04-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderate', '0003_textchat_group_identifier_textchat_group_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textchat',
            old_name='moderated_by',
            new_name='bot',
        ),
        migrations.RemoveField(
            model_name='textchat',
            name='group_identifier',
        ),
        migrations.RemoveField(
            model_name='textchat',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='textchat',
            name='platform',
        ),
    ]
